# Generated by Django 5.1.6 on 2025-09-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dashboardbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timetables/'),
        ),
    ]
