# Generated by Django 6.0.1 on 2026-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_admin_user_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('hod', 'HOD'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
