# Generated by Django 6.0.1 on 2026-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_reg_no_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('CPS1', 'CPS1'), ('CPS2', 'CPS2'), ('CPS3', 'CPS3'), ('CPS4', 'CPS4'), ('CPS5', 'CPS5'), ('CPS6', 'CPS6')], max_length=10)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period1', models.CharField(blank=True, max_length=50)),
                ('period2', models.CharField(blank=True, max_length=50)),
                ('period3', models.CharField(blank=True, max_length=50)),
                ('period4', models.CharField(blank=True, max_length=50)),
                ('period5', models.CharField(blank=True, max_length=50)),
                ('period6', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(blank=True, choices=[('CPS1', 'CPS1'), ('CPS2', 'CPS2'), ('CPS3', 'CPS3'), ('CPS4', 'CPS4'), ('CPS5', 'CPS5'), ('CPS6', 'CPS6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('hod', 'HOD')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
